version: "3.8"
services:
  download_backups:
    container_name: download_backups
    image: cirrusci/wget
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
    working_dir: /backups
    command: wget -N -i download.txt

  mssql:
    container_name: mssql_database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ABC123def
    volumes:
      - type: bind
        source: ./data
        target: /var/opt/mssql/data
      - type: bind
        source: ./backups
        target: /var/opt/mssql/backups
      - type: bind
        source: ./scripts
        target: /scripts
    command: /scripts/load-databases.sh
    depends_on:
      - download_backups
